hide_topic_footer_controls:
  default: true
  description: "Hides the reply/bookmark/share buttons at the bottom of each topic"

show_like_count:
  default: true
  description: "Shows the like count before the reply count in the topic list"

svg_icons:
  default: "far-heart|far-comment|far-share-from-square"
  type: list
  list_type: compact
